### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by cestrensem**
Hey, I have updated iconpack from original emojione repo

### CODE REVIEW

**Comment by franzliedke** [comment]
:+1: Thanks!

**Comment by franzliedke** [comment]
@cestrensem Hmm, where did you get this list from? My local installation seems to have some trouble loading some of the PNGs correctly...

**Comment by cestrensem** [comment]
@franzliedke, I found in here: https://github.com/Ranks/emojione/blob/master/lib/php/src/Ruleset.php

**Comment by franzliedke** [comment]
Okay, cool. Does the `:one:` emoji load an image for you?

**Comment by cestrensem** [comment]
Now it is not work on autocomplete drodown but it all ok with post body (((. 
Try to change 77 line on `addComposerAutocomplete.js`
```
const imageName = (emojiMap[key].indexOf('-20e3') != -1 || emojiMap[key] == 'a9' || emojiMap[key] == 'ae' ? '00' : '') + emojiMap[key];
```
to 
```
const imageName = (emojiMap[key] == 'a9' || emojiMap[key] == 'ae' ? '00' : '') + emojiMap[key];
```

**Comment by franzliedke** [comment]
Yeah, I found that, too, and [just updated it](https://github.com/flarum/flarum-ext-emoji/commit/4d7ec5d78a95863239c1bd4d6304aa3f5641a74a).

Are you sure the other special case is still needed?

**Comment by cestrensem** [comment]
And I found that in some cases autocomplete works strange. For example:
1, write :unicorn_face
2. click on it icon in the dropdown
3. nothing happend on the preview mode (

Plugin generates emoji url with uppercased emoji code, but sometimes there is no such image on the cdn: https://cdn.jsdelivr.net/emojione/assets/png/1F984.png. https://cdn.jsdelivr.net/emojione/assets/png/1f984.png is ok :confused: 

I think this this cases are reated.

**Comment by franzliedke** [comment]
Hmm, apparently TextFormatter's emojione plugin is not quite as up-to-date as this one.

ping @JoshyPHP

**Comment by JoshyPHP** [comment]
The aliases are taken from Gemoji's database, on which EmojiOne's and Twemoji's are based. It seems they have a couple of small differences though. I've added EmojiOne's database to my maintenance script so `:unicorn:` will be supported in the next release.

I've also updated the template to use lowercase filenames. Actually I was the one who [suggested they use lowercase filenames](https://github.com/Ranks/emojione/issues/133) but I forgot to update the template when they did. :sweat_smile:

**Pull request merged**
